export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const VIEW_AS = "VIEW_AS";

export const SORT_BY = "SORT_BY";

export const SET_PRICE_FILTER = "SET_PRICE_FILTER";
export const SET_CATEGORIES_FILTER = "SET_CATEGORIES_FILTER";
export const SET_PRICE = "SET_PRICE";
export const SET_FILTERED_PRODUCTS = "SET_FILTERED_PRODUCTS";

export const ADD_TO_SHOPPING_CART = "ADD_TO_SHOPPING_CART";
export const EDIT_PRODUCT_QUANTITY_IN_SHOPPING_CART = "EDIT_PRODUCT_QUANTITY_IN_SHOPPING_CART";
export const DELETE_FROM_SHOPPING_CART = "DELETE_FROM_SHOPPING_CART";
export const CLEAR_SHOPPING_CART = "CLEAR_SHOPPING_CART";